debug: false
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.project.board: debug
    org.springframework.web.server: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: noose
    password: a81637
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  sql.init.mode: always
  # thymeleaf.cache: false
  data:
    rest:
      base-path: /api
      detection-strategy: annotated

  thymeleaf3:
    decoupled-logic: true

---

spring:
  config.activate.on-profile: heroku
  datasource:
    url: ${JAWSDB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
  sql.init.mode: always
